[params]
  favicon = "static/favicon.png"

[build]
  command = "hugo --gc --minify -b $URL && npx pagefind --source 'public'"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.126.3"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL && npx pagefind --source 'public'"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL && npx pagefind --source 'public'"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

# Essentially Minimal theme but with constant home section bg color.
name = "Starter Blog"

[light]
  # Primary
  primary = "#2962ff"

  # Menu
  menu_primary = "rgb(247, 250, 252)"
  menu_text = "#34495e"
  menu_text_active = "#2962ff"
  menu_title = "#2b2b2b"

  # Home sections
  home_section_odd = "rgb(247, 250, 252)"
  home_section_even = "rgb(247, 250, 252)"

[dark]
  primary = "#bbdefb"
  link = "#bbdefb"
  link_hover = "#bbdefb"
  background = "rgb(26, 32, 44)"
  home_section_odd = "rgb(26, 32, 44)"
  home_section_even = "rgb(26, 32, 44)"
  menu_primary = "rgb(26, 32, 44)"